<!DOCTYPE html>
<html lang="hy">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>‘±’¶’°’ø’´ ÷Ü’´’¨’¥’•÷Ä’´ ’Ø’°’µ÷Ñ</title>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Roboto:wght@400;500&display=swap" rel="stylesheet" />
    <style>
        /* ‘≤’°’¶’°’µ’´’∂ ’Ω’ø’´’¨’•÷Ä */
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f2f3f7;
            color: #333;
            line-height: 1.6;
        }
        h1 {
            font-family: 'Playfair Display', serif;
            font-size: 2.5rem;
            text-align: center;
            margin-top: 40px;
            color: #2c3e50;
        }
        /* ‘ø’°’º’∏÷Ç÷Å’∏÷Ç’¥ ’•’∂÷Ñ ’Ø’∏’∂’ø’•’µ’∂’•÷Ä ÷Ü’´’¨’¥’•÷Ä’´ ’∞’°’¥’°÷Ä */
        .container {
            max-width: 1200px;
            margin: 30px auto;
            padding: 0 20px;
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
        }
        /* ’ñ’´’¨’¥’´ ÷Ñ’°÷Ä’ø */
        .movie {
            background: #ffffff;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }
        .movie:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);
        }
        .movie img {
            width: 100%;
            height: auto;
            display: block;
        }
        .movie-content {
            padding: 15px;
        }
        .movie h3 {
            font-family: 'Playfair Display', serif;
            font-size: 1.4rem;
            margin-bottom: 8px;
            color: #34495e;
        }
        .movie p {
            font-size: 0.95rem;
            margin-bottom: 6px;
            color: #555;
        }
        .movie .year {
            font-weight: 500;
            color: #7f8c8d;
        }
        /* Footer */
        footer {
            text-align: center;
            margin: 50px 0 20px 0;
            font-size: 0.9rem;
            color: #777;
        }
        footer a {
            color: #3498db;
            text-decoration: none;
        }
        footer a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h1>‘≤’°÷Ä’´ ’£’°’¨’∏÷Ç’Ω’ø ‘±’¶’°’ø’´ ’ñ’´’¨’¥’•÷Ä’´ ‘ø’°’µ÷Ñ üé¨</h1>

    <div class="container">
        <div class="movie">
            <img src="https://via.placeholder.com/300x450" alt="’ñ’´’¨’¥ 1" />
            <div class="movie-content">
                <h3>’ñ’´’¨’¥’´ ‘±’∂’æ’°’∂’∏÷Ç’¥ 1</h3>
                <p>’Ü’Ø’°÷Ä’°’£÷Ä’∏÷Ç’©’µ’∏÷Ç’∂: ’ç’° ’∞’´’°’∂’°’¨’´ ’°’º’°’ª’´’∂ ÷Ü’´’¨’¥’∂ ’ß, ’∏÷Ä’® ’Ω’ø’•’≤’Æ’æ’•’¨ ’ß ’¥’•÷Ä ’∞’°’µ’°÷Å÷Ñ’∏’æ ‚Ä¶</p>
                <p class="year">’è’°÷Ä’´’ù 2023</p>
            </div>
        </div>
        <div class="movie">
            <img src="https://via.placeholder.com/300x450" alt="’ñ’´’¨’¥ 2" />
            <div class="movie-content">
                <h3>’ñ’´’¨’¥’´ ‘±’∂’æ’°’∂’∏÷Ç’¥ 2</h3>
                <p>’Ü’Ø’°÷Ä’°’£÷Ä’∏÷Ç’©’µ’∏÷Ç’∂: ‘µ÷Ä’Ø÷Ä’∏÷Ä’§ ÷Ü’´’¨’¥’´ ’¥’°’Ω’´’∂ ’°’∂’±’∂’°’Ø’°’∂ ’Ø’°÷Ä’Æ’´÷Ñ, ’∞’´’¥’∂’°’Ø’°’∂ ’Ø’•’ø’•÷Ä’® ÷á ’Ω’µ’∏÷Ç’™’•’∂’•÷Ä’´ ’¥’°’Ω’´’∂ ’Ø’°÷Ä’≥ ‚Ä¶</p>
                <p class="year">’è’°÷Ä’´’ù 2022</p>
            </div>
        </div>
        <div class="movie">
            <img src="https://via.placeholder.com/300x450" alt="’ñ’´’¨’¥ 3" />
            <div class="movie-content">
                <h3>’ñ’´’¨’¥’´ ‘±’∂’æ’°’∂’∏÷Ç’¥ 3</h3>
                <p>’Ü’Ø’°÷Ä’°’£÷Ä’∏÷Ç’©’µ’∏÷Ç’∂: ‘µ÷Ä÷Ä’∏÷Ä’§ ÷Ü’´’¨’¥’´ ’∞’•’ø’°÷Ñ÷Ä÷Ñ’´÷Ä ’ø’æ’µ’°’¨’∂’•÷Ä, ’£’¨’≠’°’æ’∏÷Ä ’§’•÷Ä’°’Ω’°’∂’∂’•÷Ä ÷á ’º’•’™’´’Ω’∏÷Ä ‚Ä¶</p>
                <p class="year">’è’°÷Ä’´’ù 2021</p>
            </div>
        </div>
        <!-- ‘ø’°÷Ä’∏’≤ ’•’Ω ’°’∂’Ω’°’∞’¥’°’∂ ’°’æ’•’¨’°÷Å’∂’•’¨ ’∂’∏÷Ä .movie ’°÷Ä’Ø’≤’•÷Ä -->
    </div>

    <footer>
        <p>¬© 2025 ‘±’¶’°’ø ‚Äì <a href="https://zaz33.github.io">zaz33.github.io</a></p>
    </footer>
</body>
</html>
